[package]
name = "inbox3"
version = "1.0.0"
authors = []

[addresses]
inbox3 = "0x2fb49669a943f53c7a0ab469e3fc475b273697f0151554e8321646895ca55d0e"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "devnet"
subdir = "aptos-framework"

[dev-dependencies]
